"""
AI Orchestrator — Central intelligence for contact pipeline management.

Auto-moves contacts through pipeline stages based on conversation context,
detects problematic chats, triggers follow-ups, and sends webhook alerts.

Pipeline stages (auto-managed):
    NOVO → EM_CONTATO → QUALIFICADO → PROPOSTA → FECHADO
                ↓              ↓           ↓
             PERDIDO       PERDIDO     PERDIDO
"""

import json
import logging
import time
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Dict, List, Optional, Set

from app.core.config import settings

logger = logging.getLogger(__name__)


class PipelineStage(str, Enum):
    NOVO = "NOVO"
    EM_CONTATO = "EM_CONTATO"
    QUALIFICADO = "QUALIFICADO"
    PROPOSTA = "PROPOSTA"
    FECHADO = "FECHADO"
    PERDIDO = "PERDIDO"


class AlertSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class ConversationState:
    """Tracks the state of a single conversation for orchestration."""

    __slots__ = (
        "session_id", "chat_jid", "contact_name", "contact_phone",
        "pipeline_stage", "last_message_at", "last_ai_response_at",
        "message_count", "detected_intent", "intent_confidence",
        "angry_signals", "confusion_signals", "repeated_count",
        "escalation_requested", "operator_taken_over",
        "follow_up_due_at", "created_at",
    )

    def __init__(self, session_id: str, chat_jid: str, contact_name: str = "", contact_phone: str = ""):
        self.session_id = session_id
        self.chat_jid = chat_jid
        self.contact_name = contact_name
        self.contact_phone = contact_phone
        self.pipeline_stage = PipelineStage.NOVO
        self.last_message_at: Optional[datetime] = None
        self.last_ai_response_at: Optional[datetime] = None
        self.message_count = 0
        self.detected_intent: Optional[str] = None
        self.intent_confidence: float = 0.0
        self.angry_signals = 0
        self.confusion_signals = 0
        self.repeated_count = 0
        self.escalation_requested = False
        self.operator_taken_over = False
        self.follow_up_due_at: Optional[datetime] = None
        self.created_at = datetime.utcnow()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "session_id": self.session_id,
            "chat_jid": self.chat_jid,
            "contact_name": self.contact_name,
            "contact_phone": self.contact_phone,
            "pipeline_stage": self.pipeline_stage.value,
            "last_message_at": self.last_message_at.isoformat() if self.last_message_at else None,
            "last_ai_response_at": self.last_ai_response_at.isoformat() if self.last_ai_response_at else None,
            "message_count": self.message_count,
            "detected_intent": self.detected_intent,
            "intent_confidence": self.intent_confidence,
            "angry_signals": self.angry_signals,
            "confusion_signals": self.confusion_signals,
            "repeated_count": self.repeated_count,
            "escalation_requested": self.escalation_requested,
            "operator_taken_over": self.operator_taken_over,
            "follow_up_due_at": self.follow_up_due_at.isoformat() if self.follow_up_due_at else None,
            "created_at": self.created_at.isoformat(),
        }


class Alert:
    """An alert generated by the orchestrator."""

    def __init__(self, severity: AlertSeverity, title: str, message: str, conversation_key: str, metadata: Dict = None):
        self.severity = severity
        self.title = title
        self.message = message
        self.conversation_key = conversation_key
        self.metadata = metadata or {}
        self.timestamp = datetime.utcnow()


class OrchestratorMetrics:
    """Tracks orchestrator performance metrics."""

    def __init__(self):
        self.conversations_tracked = 0
        self.stage_transitions = 0
        self.alerts_generated = 0
        self.follow_ups_triggered = 0
        self.problematic_chats_detected = 0
        self.start_time = datetime.utcnow()

    def to_prometheus(self) -> str:
        """Export metrics in Prometheus format."""
        uptime = (datetime.utcnow() - self.start_time).total_seconds()
        return f"""# HELP afiliators_orchestrator_conversations Total tracked conversations
# TYPE afiliators_orchestrator_conversations gauge
afiliators_orchestrator_conversations {self.conversations_tracked}
# HELP afiliators_orchestrator_stage_transitions Total stage transitions
# TYPE afiliators_orchestrator_stage_transitions counter
afiliators_orchestrator_stage_transitions_total {self.stage_transitions}
# HELP afiliators_orchestrator_alerts Total alerts generated
# TYPE afiliators_orchestrator_alerts counter
afiliators_orchestrator_alerts_total {self.alerts_generated}
# HELP afiliators_orchestrator_follow_ups Total follow-ups triggered
# TYPE afiliators_orchestrator_follow_ups counter
afiliators_orchestrator_follow_ups_total {self.follow_ups_triggered}
# HELP afiliators_orchestrator_problematic_chats Detected problematic chats
# TYPE afiliators_orchestrator_problematic_chats counter
afiliators_orchestrator_problematic_chats_total {self.problematic_chats_detected}
# HELP afiliators_orchestrator_uptime_seconds Uptime in seconds
# TYPE afiliators_orchestrator_uptime_seconds gauge
afiliators_orchestrator_uptime_seconds {uptime}
"""


class AIOrchestrator:
    """
    Central AI Orchestrator that manages the entire contact lifecycle.

    Responsibilities:
    1. Auto-advance pipeline stages based on intent + engagement
    2. Detect problematic chats (angry users, AI confusion, repeated messages)
    3. Trigger follow-ups for stale conversations
    4. Generate webhook alerts for operator intervention
    5. Track metrics for monitoring
    """

    # Intent → Pipeline stage mapping
    INTENT_TO_STAGE: Dict[str, PipelineStage] = {
        "greeting": PipelineStage.EM_CONTATO,
        "lead_interest": PipelineStage.QUALIFICADO,
        "payment": PipelineStage.PROPOSTA,
        "schedule": PipelineStage.PROPOSTA,
        "complaint": PipelineStage.EM_CONTATO,
        "follow_up": PipelineStage.EM_CONTATO,
    }

    # Words/signals that indicate user is angry
    ANGRY_SIGNALS = {
        "palhaçada", "ridículo", "absurdo", "processo", "advogado",
        "procon", "reclame aqui", "enganação", "golpe", "fraude",
        "dinheiro de volta", "estorno", "cancelar", "cancelamento",
        "não resolve", "ninguém responde", "ignorado", "descaso",
    }

    # Signals that AI is confused / not helping
    CONFUSION_SIGNALS = {
        "não foi isso que eu perguntei", "você não entendeu",
        "já falei isso", "repetindo", "não é isso",
        "?", "??", "???", "não entendi", "como assim",
    }

    def __init__(self):
        self._conversations: Dict[str, ConversationState] = {}
        self._alerts: List[Alert] = []
        self.metrics = OrchestratorMetrics()
        self._initialized = False

    async def initialize(self):
        if self._initialized:
            return
        self._initialized = True
        logger.info("AI Orchestrator initialized — pipeline management active")

    # ==================== CONVERSATION TRACKING ====================

    def get_or_create_conversation(
        self, session_id: str, chat_jid: str,
        contact_name: str = "", contact_phone: str = ""
    ) -> ConversationState:
        key = f"{session_id}:{chat_jid}"
        if key not in self._conversations:
            self._conversations[key] = ConversationState(
                session_id, chat_jid, contact_name, contact_phone
            )
            self.metrics.conversations_tracked += 1
            logger.info("New conversation tracked: %s", key)
        return self._conversations[key]

    def get_conversation(self, session_id: str, chat_jid: str) -> Optional[ConversationState]:
        return self._conversations.get(f"{session_id}:{chat_jid}")

    def get_all_conversations(self) -> List[ConversationState]:
        return list(self._conversations.values())

    # ==================== PIPELINE MANAGEMENT ====================

    def process_incoming_message(
        self, session_id: str, chat_jid: str,
        message_text: str, detected_intent: Optional[str] = None,
        intent_confidence: float = 0.0,
        contact_name: str = "", contact_phone: str = ""
    ) -> Dict[str, Any]:
        """
        Process an incoming message through the orchestrator.

        Returns a dict with pipeline updates, alerts, and suggested actions.
        """
        conv = self.get_or_create_conversation(
            session_id, chat_jid, contact_name, contact_phone
        )

        conv.message_count += 1
        conv.last_message_at = datetime.utcnow()

        if detected_intent:
            conv.detected_intent = detected_intent
            conv.intent_confidence = intent_confidence

        # Auto-advance pipeline based on intent
        stage_changed = self._auto_advance_stage(conv, detected_intent, message_text)

        # Detect issues
        alerts = self._detect_issues(conv, message_text)

        # Schedule follow-up if needed
        follow_up = self._schedule_follow_up(conv)

        result = {
            "pipeline_stage": conv.pipeline_stage.value,
            "stage_changed": stage_changed,
            "message_count": conv.message_count,
            "alerts": [{"severity": a.severity.value, "title": a.title} for a in alerts],
            "follow_up_due": conv.follow_up_due_at.isoformat() if conv.follow_up_due_at else None,
        }

        if stage_changed:
            logger.info(
                "Pipeline stage transition: %s → %s (intent: %s, confidence: %.2f)",
                conv.chat_jid, conv.pipeline_stage.value,
                detected_intent, intent_confidence,
            )
            self.metrics.stage_transitions += 1

        if alerts:
            self.metrics.alerts_generated += len(alerts)
            for alert in alerts:
                self._alerts.append(alert)
                self._send_webhook_alert(alert)

        return result

    def process_ai_response(
        self, session_id: str, chat_jid: str, response_text: str
    ):
        """Mark that the AI has responded to this conversation."""
        conv = self.get_conversation(session_id, chat_jid)
        if conv:
            conv.last_ai_response_at = datetime.utcnow()

    def mark_operator_takeover(self, session_id: str, chat_jid: str):
        """Mark a conversation as taken over by a human operator."""
        conv = self.get_conversation(session_id, chat_jid)
        if conv:
            conv.operator_taken_over = True
            logger.info("Operator takeover: %s:%s", session_id, chat_jid)

    def mark_operator_return(self, session_id: str, chat_jid: str):
        """Mark a conversation as returned to AI."""
        conv = self.get_conversation(session_id, chat_jid)
        if conv:
            conv.operator_taken_over = False
            logger.info("Operator return to AI: %s:%s", session_id, chat_jid)

    # ==================== STALE DETECTION ====================

    def find_stale_conversations(self) -> List[ConversationState]:
        """Find conversations that need follow-up (stale)."""
        stale = []
        cutoff = datetime.utcnow() - timedelta(minutes=settings.CONVERSATION_STALE_MINUTES)
        for conv in self._conversations.values():
            if conv.operator_taken_over:
                continue
            if conv.pipeline_stage in (PipelineStage.FECHADO, PipelineStage.PERDIDO):
                continue
            if conv.last_message_at and conv.last_message_at < cutoff:
                stale.append(conv)
        return stale

    def find_dead_conversations(self) -> List[ConversationState]:
        """Find conversations that should be archived (dead)."""
        dead = []
        cutoff = datetime.utcnow() - timedelta(minutes=settings.CONVERSATION_DEAD_MINUTES)
        for conv in self._conversations.values():
            if conv.last_message_at and conv.last_message_at < cutoff:
                if conv.pipeline_stage not in (PipelineStage.FECHADO, PipelineStage.PERDIDO):
                    dead.append(conv)
        return dead

    # ==================== INTERNAL METHODS ====================

    def _auto_advance_stage(
        self, conv: ConversationState,
        intent: Optional[str], message_text: str
    ) -> bool:
        """Auto-advance pipeline stage based on intent and engagement."""
        if conv.operator_taken_over:
            return False

        old_stage = conv.pipeline_stage

        # First contact → EM_CONTATO
        if conv.message_count == 1 and conv.pipeline_stage == PipelineStage.NOVO:
            conv.pipeline_stage = PipelineStage.EM_CONTATO
            return True

        # Intent-based advancement
        if intent and intent in self.INTENT_TO_STAGE:
            target = self.INTENT_TO_STAGE[intent]
            stage_order = list(PipelineStage)
            if stage_order.index(target) > stage_order.index(conv.pipeline_stage):
                conv.pipeline_stage = target
                return True

        # High engagement → advance
        if conv.message_count >= 5 and conv.pipeline_stage == PipelineStage.EM_CONTATO:
            conv.pipeline_stage = PipelineStage.QUALIFICADO
            return True

        if conv.message_count >= 10 and conv.pipeline_stage == PipelineStage.QUALIFICADO:
            conv.pipeline_stage = PipelineStage.PROPOSTA
            return True

        return old_stage != conv.pipeline_stage

    def _detect_issues(self, conv: ConversationState, message_text: str) -> List[Alert]:
        """Detect problematic patterns in conversations."""
        alerts = []
        msg_lower = message_text.lower()
        key = f"{conv.session_id}:{conv.chat_jid}"

        # Angry user detection
        angry_matches = [s for s in self.ANGRY_SIGNALS if s in msg_lower]
        if angry_matches:
            conv.angry_signals += len(angry_matches)
            if conv.angry_signals >= 2:
                alerts.append(Alert(
                    AlertSeverity.CRITICAL,
                    "Usuário irritado detectado",
                    f"Contato {conv.contact_name or conv.chat_jid} demonstrou sinais de irritação: {', '.join(angry_matches[:3])}. Considere intervenção humana.",
                    key,
                    {"angry_signals": angry_matches},
                ))
                self.metrics.problematic_chats_detected += 1

        # AI confusion detection
        confusion_matches = [s for s in self.CONFUSION_SIGNALS if s in msg_lower]
        if confusion_matches:
            conv.confusion_signals += len(confusion_matches)
            if conv.confusion_signals >= 3:
                alerts.append(Alert(
                    AlertSeverity.WARNING,
                    "Possível confusão da IA",
                    f"Usuário {conv.contact_name or conv.chat_jid} parece insatisfeito com as respostas. Verifique a conversa.",
                    key,
                    {"confusion_signals": confusion_matches},
                ))
                self.metrics.problematic_chats_detected += 1

        # Repeated messages (user sending same thing)
        # Simplified: detect repetition patterns
        words = msg_lower.split()
        if len(words) > 3 and len(set(words)) < len(words) * 0.4:
            conv.repeated_count += 1
            if conv.repeated_count >= 3:
                alerts.append(Alert(
                    AlertSeverity.WARNING,
                    "Mensagens repetitivas",
                    f"Usuário {conv.contact_name or conv.chat_jid} está enviando mensagens repetitivas.",
                    key,
                ))

        # Escalation request
        escalation_keywords = {"humano", "atendente", "pessoa", "gerente", "supervisor", "falar com", "quero falar"}
        if any(kw in msg_lower for kw in escalation_keywords):
            conv.escalation_requested = True
            alerts.append(Alert(
                AlertSeverity.CRITICAL,
                "Solicitação de atendente humano",
                f"Contato {conv.contact_name or conv.chat_jid} pediu para falar com um atendente humano.",
                key,
                {"escalation": True},
            ))
            self.metrics.problematic_chats_detected += 1

        return alerts

    def _schedule_follow_up(self, conv: ConversationState) -> bool:
        """Schedule automated follow-up based on pipeline stage."""
        if conv.operator_taken_over:
            return False
        if conv.pipeline_stage in (PipelineStage.FECHADO, PipelineStage.PERDIDO):
            return False
        if conv.follow_up_due_at:
            return False

        # Schedule follow-up based on stage
        delays = {
            PipelineStage.NOVO: timedelta(hours=4),
            PipelineStage.EM_CONTATO: timedelta(hours=24),
            PipelineStage.QUALIFICADO: timedelta(hours=48),
            PipelineStage.PROPOSTA: timedelta(hours=72),
        }
        delay = delays.get(conv.pipeline_stage, timedelta(hours=24))
        conv.follow_up_due_at = datetime.utcnow() + delay
        self.metrics.follow_ups_triggered += 1
        logger.info("Follow-up scheduled for %s at %s", conv.chat_jid, conv.follow_up_due_at)
        return True

    def _send_webhook_alert(self, alert: Alert):
        """Send alert via webhook if configured."""
        if not settings.WEBHOOK_ALERT_URL:
            return
        try:
            import aiohttp
            async def send():
                async with aiohttp.ClientSession() as session:
                    await session.post(
                        settings.WEBHOOK_ALERT_URL,
                        json={
                            "severity": alert.severity.value,
                            "title": alert.title,
                            "message": alert.message,
                            "conversation": alert.conversation_key,
                            "timestamp": alert.timestamp.isoformat(),
                            "metadata": alert.metadata,
                        },
                        timeout=aiohttp.ClientTimeout(total=5),
                    )
            # Fire and forget
            import asyncio
            try:
                loop = asyncio.get_event_loop()
                if loop.is_running():
                    asyncio.create_task(send())
            except RuntimeError:
                pass
        except ImportError:
            logger.debug("aiohttp not available — webhook skipped")

    # ==================== METRICS & MONITORING ====================

    def get_metrics(self) -> OrchestratorMetrics:
        return self.metrics

    def get_alerts(self, severity: Optional[AlertSeverity] = None, limit: int = 50) -> List[Alert]:
        alerts = self._alerts
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        return alerts[-limit:]

    def get_pipeline_summary(self) -> Dict[str, int]:
        """Count conversations per pipeline stage."""
        counts = {stage.value: 0 for stage in PipelineStage}
        for conv in self._conversations.values():
            counts[conv.pipeline_stage.value] += 1
        return counts

    def get_health(self) -> Dict[str, Any]:
        """Health check for the orchestrator."""
        total = len(self._conversations)
        problematic = sum(
            1 for c in self._conversations.values()
            if c.angry_signals > 0 or c.confusion_signals > 0 or c.escalation_requested
        )
        return {
            "initialized": self._initialized,
            "conversations_tracked": total,
            "problematic_conversations": problematic,
            "alerts_pending": len(self._alerts),
            "uptime_seconds": (datetime.utcnow() - self.metrics.start_time).total_seconds(),
            "pipeline_summary": self.get_pipeline_summary(),
        }


# Global singleton
orchestrator = AIOrchestrator()
